// Copy slots for /ways-to-give (src/lib/copy.ts). SEO defaults are the live site's
// values (src/data/page-seo.json, from the Webflow migration).
import { defineCopy, seoSlots } from '../../lib/copy'

export default defineCopy('/ways-to-give', {
  ...seoSlots({
    title: 'Ways to Give | Victoria Venezuela Foundation',
    description: 'Give once, give monthly, sponsor a child, or give through your employer. Every gift reaches children in Venezuela.',
    image: '/images/pages/57692375-vvf-home-shareimage-v2.jpg',
  }),
  'hero.imageAlt': { label: 'Hero: image description', default: 'Baby in pink dress held near red and white balloons and a large striped candy cane balloon.', maxLength: 140 },
  'hero.heading': { label: 'Hero: heading', default: 'Ways to give', maxLength: 20 },
  'hero.subtext': { label: 'Hero: text', default: 'Every gift reaches children in Venezuela. Choose the way that works for you.', maxLength: 120 },
  'hero.label.1': { label: 'Hero: button 1', default: 'Give now', maxLength: 20 },
  'hero.label.2': { label: 'Hero: button 2', default: 'Sponsor a child', maxLength: 30 },
  'featureBand.tagline': { label: 'Feature band: tagline', default: 'Donate', maxLength: 20 },
  'featureBand.heading': { label: 'Feature band: heading', default: 'Make a gift today', maxLength: 30 },
  'featureBand.text': { label: 'Feature band: text', default: 'Choose an amount and give in under a minute. Every gift funds meals, medical care and schooling for children in Venezuela.', maxLength: 190 },
  'featureBand.imageAlt': { label: 'Feature band: image description', default: 'Smiling young girl with pigtails playing inside a colorful inflatable bounce house.', maxLength: 130 },
  'p.text': { label: 'P: text', default: 'Would you rather give every month?', maxLength: 60 },
  'a.text': { label: 'A: text', default: 'Sponsor a child for $25 a month.', maxLength: 50 },
  'p2.text': { label: 'P 2: text', default: 'Payment is handled by Donorbox. Victoria Venezuela Foundation is a 501(c)(3) non-profit organization, Tax ID 88-3282100, and your gift is tax-deductible in the United States.', maxLength: 270 },
  'mediaSplit.tagline': { label: 'Media split: tagline', default: 'Sponsorship', maxLength: 20 },
  'mediaSplit.heading': { label: 'Media split: heading', default: 'Sponsor a child for $25 a month', maxLength: 50 },
  'mediaSplit.text': { label: 'Media split: text', default: "Choose a child and support them every month. Your gift joins other sponsors' to fund the meals, medical care and schooling that reach them, and you get letters, photos and updates on how they are doing.", maxLength: 310 },
  'mediaSplit.note': { label: 'Media split: note', default: 'A child is usually supported by more than one sponsor, and we direct funds to where the need is greatest. You can stop at any time.', maxLength: 200 },
  'mediaSplit.imageAlt': { label: 'Media split: image description', default: 'Smiling boy holding cotton candy with children playing near an inflatable bounce house outdoors.', maxLength: 150 },
  'button.text': { label: 'Button: text', default: 'Meet the children', maxLength: 30 },
  'sectionTitle.tagline': { label: 'Section title: tagline', default: 'More ways', maxLength: 20 },
  'sectionTitle.heading': { label: 'Section title: heading', default: 'Other ways to give', maxLength: 30 },
  'pastelCard.title': { label: 'Pastel card: title', default: 'Employer matching', maxLength: 30 },
  'pastelCard.body': { label: 'Pastel card: body', default: 'Many companies double what their employees give. Search for your employer and find out in a few seconds.', maxLength: 160 },
  'pastelCard2.title': { label: 'Pastel card 2: title', default: 'Donor-advised fund', maxLength: 30 },
  'pastelCard2.body': { label: 'Pastel card 2: body', default: 'Direct your charitable giving from your DAF account using our EIN, 88-3282100. We will help you complete the designation.', maxLength: 190 },
  'pastelCard2.label.1': { label: 'Pastel card 2: button 1', default: 'Ask us for help', maxLength: 30 },
  'pastelCard3.title': { label: 'Pastel card 3: title', default: 'Corporate partnership', maxLength: 40 },
  'pastelCard3.body': { label: 'Pastel card 3: body', default: 'Tiered sponsorships with visibility and employee engagement, plus event sponsorship and matching gifts.', maxLength: 160 },
  'pastelCard3.label.1': { label: 'Pastel card 3: button 1', default: 'Partner with us', maxLength: 30 },
  'featureBand2.tagline': { label: 'Feature band 2: tagline', default: 'Come and give', maxLength: 20 },
  'featureBand2.imageAlt': { label: 'Feature band 2: image description', default: 'Golfers standing by the lake at the Victoria Venezuela Foundation charity golf tournament, holding Venezuelan flags.', maxLength: 180 },
  'button2.text': { label: 'Button 2: text', default: 'More Info', maxLength: 20 },
  'appealPanel.heading': { label: 'Appeal panel: heading', default: 'Venezuela earthquake relief', maxLength: 50 },
  'appealPanel.text': { label: 'Appeal panel: text', default: "Funds raised from this campaign will go towards the construction of VVF's permanent support centre in La Guaira. When it opens it will provide shelter, nutrition and medical care to 500 displaced children and their families.", maxLength: 340 },
  'appealPanel.imageAlt': { label: 'Appeal panel: image description', default: 'Render of the planned VVF support centre in La Guaira, seen from the street.', maxLength: 120 },
  'appealPanel.caption': { label: 'Appeal panel: caption', default: 'How the centre in La Guaira will look. The centre is not built yet. All images on this page are AI-generated renders.', maxLength: 180 },
  'appealPanel.title.1': { label: 'Appeal panel: title 1', default: 'Shelter', maxLength: 20 },
  'appealPanel.text.1': { label: 'Appeal panel: text 1', default: 'A safe place to stay for families whose homes were destroyed in the June 2026 earthquakes.', maxLength: 140 },
  'appealPanel.imageAlt.1': { label: 'Appeal panel: image description 1', default: 'Families arriving at the courtyard of the planned VVF support centre.', maxLength: 110 },
  'appealPanel.title.2': { label: 'Appeal panel: title 2', default: 'Medical care', maxLength: 20 },
  'appealPanel.text.2': { label: 'Appeal panel: text 2', default: 'Check-ups, medicine and treatment for children and their families at the center.', maxLength: 120 },
  'appealPanel.imageAlt.2': { label: 'Appeal panel: image description 2', default: 'A nurse examining a young girl while her mother sits beside her.', maxLength: 100 },
  'appealPanel.title.3': { label: 'Appeal panel: title 3', default: 'Nutrition', maxLength: 20 },
  'appealPanel.text.3': { label: 'Appeal panel: text 3', default: 'Daily meals for the children staying at the support center in La Guaira.', maxLength: 110 },
  'appealPanel.label.1': { label: 'Appeal panel: button 1', default: 'Give to the appeal', maxLength: 30 },
  'appealPanel.label.2': { label: 'Appeal panel: button 2', default: 'Learn More', maxLength: 20 },
  'sectionTitle2.heading': { label: 'Section title 2: heading', default: 'Frequently asked questions', maxLength: 40 },
  'appealPanel.cardsLabel': { label: 'Appeal panel: cardsLabel', default: 'What your gift will pay for', maxLength: 50 },
  'pastelCard.label.1': { label: "Pastel card: button 1", default: "Let's check", maxLength: 20 },
  'appealPanel.cards.nutritionAlt': { label: "Appeal panel: nutrition card image description", default: "Children eating a hot meal together in the centre's dining room.", maxLength: 100 },
})
