// Copy slots for /sponsor-a-child (src/lib/copy.ts). SEO defaults are the live site's
// values (src/data/page-seo.json, from the Webflow migration).
import { defineCopy, seoSlots } from '../../lib/copy'

export default defineCopy('/sponsor-a-child', {
  ...seoSlots({
    title: 'Sponsor a Child in Venezuela | Victoria Venezuela Foundation',
    description: 'Sponsor a child in Venezuela from $25 a month. Your gift funds weekly meals, medical checkups twice a year and school support for the children in our care.',
    image: '/images/pages/57692375-vvf-home-shareimage-v2.jpg',
  }),
  'hero.imageAlt': { label: 'Hero: image description', default: 'Smiling girl sitting at a table eating empanadas with orange cups nearby.', maxLength: 110 },
  'hero.heading': { label: 'Hero: heading', default: 'Sponsor a child in Venezuela', maxLength: 50 },
  'hero.subtext': { label: 'Hero: text', default: 'Build a personal connection. Transform a life.', maxLength: 70 },
  'hero.label.1': { label: 'Hero: button 1', default: 'Meet the children', maxLength: 30 },
  'hero.label.2': { label: 'Hero: button 2', default: 'How it works', maxLength: 20 },
  'sectionTitle.tagline': { label: 'Section title: tagline', default: 'Essential', maxLength: 20 },
  'sectionTitle.heading': { label: 'Section title: heading', default: 'Every child deserves a fighting chance', maxLength: 60 },
  'sectionTitle.text': { label: 'Section title: text', default: "Sponsorship means stepping into a child's life with consistent support. You choose the amount each month, starting at just $25, and that commitment becomes the difference between survival and thriving for one young person in Venezuela.", maxLength: 360 },
  'button.text': { label: 'Button: text', default: 'Sponsor', maxLength: 20 },
  'button2.text': { label: 'Button 2: text', default: 'Learn more', maxLength: 20 },
  'sectionTitle2.tagline': { label: 'Section title 2: tagline', default: 'Children', maxLength: 20 },
  'sectionTitle2.heading': { label: 'Section title 2: heading', default: 'Meet the children', maxLength: 30 },
  'sectionTitle2.text': { label: 'Section title 2: text', default: 'Find the child who needs you most', maxLength: 50 },
  'button3.text': { label: 'Button 3: text', default: 'Meet them all', maxLength: 20 },
  'sectionTitle3.tagline': { label: 'Section title 3: tagline', default: 'Process', maxLength: 20 },
  'sectionTitle3.heading': { label: 'Section title 3: heading', default: 'Three steps to change', maxLength: 40 },
  'sectionTitle3.text': { label: 'Section title 3: text', default: 'Start here and find your match', maxLength: 50 },
  'pastelCard.eyebrow': { label: 'Pastel card: eyebrow', default: 'First', maxLength: 20 },
  'pastelCard.title': { label: 'Pastel card: title', default: 'Choose a child', maxLength: 30 },
  'pastelCard.body': { label: 'Pastel card: body', default: 'Browse the gallery and choose the child you want to support.', maxLength: 90 },
  'pastelCard2.eyebrow': { label: 'Pastel card 2: eyebrow', default: 'Second', maxLength: 20 },
  'pastelCard2.title': { label: 'Pastel card 2: title', default: 'Set your amount', maxLength: 30 },
  'pastelCard2.body': { label: 'Pastel card 2: body', default: 'You decide the monthly gift, starting at just $25', maxLength: 80 },
  'pastelCard3.eyebrow': { label: 'Pastel card 3: eyebrow', default: 'Third', maxLength: 20 },
  'pastelCard3.title': { label: 'Pastel card 3: title', default: 'Build a relationship that matters', maxLength: 50 },
  'pastelCard3.body': { label: 'Pastel card 3: body', default: 'Receive letters, photos, and watch your child grow stronger', maxLength: 90 },
  'checklistPanel.tagline': { label: 'Checklist panel: tagline', default: 'Impact', maxLength: 20 },
  'checklistPanel.heading': { label: 'Checklist panel: heading', default: 'What sponsorship provides', maxLength: 40 },
  'checklistPanel.text': { label: 'Checklist panel: text', default: 'Your commitment reaches far', maxLength: 50 },
  'checklistPanel.items.1': { label: 'Checklist panel: items 1', default: 'Weekly nutritious meals:', maxLength: 40 },
  'checklistPanel.items.2': { label: 'Checklist panel: items 2', default: 'Food that builds strength and hope', maxLength: 60 },
  'checklistPanel.items.3': { label: 'Checklist panel: items 3', default: 'Dignified access to education:', maxLength: 50 },
  'checklistPanel.items.4': { label: 'Checklist panel: items 4', default: 'Supplies, uniforms, and the tools to learn', maxLength: 70 },
  'checklistPanel.items.5': { label: 'Checklist panel: items 5', default: 'Medical checkups twice a year:', maxLength: 50 },
  'checklistPanel.items.6': { label: 'Checklist panel: items 6', default: 'A doctor sees your child twice a year, and treatment is covered when something is wrong.', maxLength: 140 },
  'checklistPanel.items.7': { label: 'Checklist panel: items 7', default: 'Connection with you:', maxLength: 30 },
  'checklistPanel.items.8': { label: 'Checklist panel: items 8', default: 'The knowledge that they matter through a real connection', maxLength: 90 },
  'checklistPanel.title.1': { label: 'Checklist panel: title 1', default: 'Weekly nutritious meals:', maxLength: 40 },
  'checklistPanel.text.1': { label: 'Checklist panel: text 1', default: 'Food that builds strength and hope', maxLength: 60 },
  'checklistPanel.title.2': { label: 'Checklist panel: title 2', default: 'Dignified access to education:', maxLength: 50 },
  'checklistPanel.text.2': { label: 'Checklist panel: text 2', default: 'Supplies, uniforms, and the tools to learn', maxLength: 70 },
  'checklistPanel.title.3': { label: 'Checklist panel: title 3', default: 'Medical checkups twice a year:', maxLength: 50 },
  'checklistPanel.text.3': { label: 'Checklist panel: text 3', default: 'A doctor sees your child twice a year, and treatment is covered when something is wrong.', maxLength: 140 },
  'checklistPanel.title.4': { label: 'Checklist panel: title 4', default: 'Connection with you:', maxLength: 30 },
  'checklistPanel.text.4': { label: 'Checklist panel: text 4', default: 'The knowledge that they matter through a real connection', maxLength: 90 },
  'sectionTitle4.tagline': { label: 'Section title 4: tagline', default: 'Rewards', maxLength: 20 },
  'sectionTitle4.heading': { label: 'Section title 4: heading', default: 'What you receive as a sponsor', maxLength: 50 },
  'sectionTitle4.text': { label: 'Section title 4: text', default: "Sponsorship is a two-way street. You give support, and you receive something equally valuable—a window into a child's world and the knowledge that you changed it.", maxLength: 250 },
  'iconCard.title': { label: 'Icon card: title', default: 'Letters from your child', maxLength: 40 },
  'iconCard.text': { label: 'Icon card: text', default: 'Words and drawings that show you matter to someone far away', maxLength: 90 },
  'iconCard2.title': { label: 'Icon card 2: title', default: 'Photos and progress updates', maxLength: 50 },
  'iconCard2.text': { label: 'Icon card 2: text', default: 'See the growth, the smile, the transformation your gift enables', maxLength: 100 },
  'iconCard3.title': { label: 'Icon card 3: title', default: 'Prayer requests and needs', maxLength: 40 },
  'iconCard3.text': { label: 'Icon card 3: text', default: 'Know how to intercede and support beyond the monthly gift', maxLength: 90 },
  'iconCard4.title': { label: 'Icon card 4: title', default: 'Annual impact reports', maxLength: 40 },
  'iconCard4.text': { label: 'Icon card 4: text', default: 'Detailed accounting of how your sponsorship changed lives this year', maxLength: 110 },
  'button4.text': { label: 'Button 4: text', default: 'Sponsor a Child', maxLength: 30 },
  'sectionTitle5.tagline': { label: 'Section title 5: tagline', default: 'Questions', maxLength: 20 },
  'sectionTitle5.heading': { label: 'Section title 5: heading', default: 'Frequently asked questions', maxLength: 40 },
  'sectionTitle5.text': { label: 'Section title 5: text', default: 'Everything you need to know about child sponsorship', maxLength: 80 },
  'h2.text': { label: 'H2: text', default: 'What if I need to cancel?', maxLength: 40 },
  'p.text': { label: 'P: text', default: "You can pause or end your sponsorship anytime with no penalty. We ask for thirty days' notice so we can help transition your child to another sponsor. Your child's care continues uninterrupted during this time.", maxLength: 320 },
  'button5.text': { label: 'Button 5: text', default: 'Still have questions?', maxLength: 40 },
  'programsCta.heading': { label: 'Programs cta: heading', default: 'We earn your trust through transparency', maxLength: 60 },
  'programsCta.text': { label: 'Programs cta: text', default: 'In fiscal 2025, 95% of funds went directly to programs. Sponsorship builds a relationship with one child. Gifts fund the programs that serve all the children in our care.', maxLength: 260 },
  'programsCta.label.1': { label: 'Programs cta: button 1', default: 'Sponsor a Child', maxLength: 30 },
  'programsCta.label.2': { label: 'Programs cta: button 2', default: 'View our financials', maxLength: 30 },
  'img.alt': { label: 'Img: image description', default: 'Three smiling girls playing on an inflatable slide at a foundation activity', maxLength: 120 },
})
