// Copy slots for /earthquake-relief (src/lib/copy.ts). SEO defaults are the live site's
// values (src/data/page-seo.json, from the Webflow migration).
import { defineCopy, seoSlots } from '../../lib/copy'

export default defineCopy('/earthquake-relief', {
  ...seoSlots({
    title: 'Venezuela Earthquake Relief | Victoria Venezuela Foundation',
    description: 'Back-to-back earthquakes hit Venezuela in June 2026. 100% of net proceeds go to relief for displaced children and families. See how to help.',
    image: '/images/pages/57692375-vvf-home-shareimage-v2.jpg',
  }),
  'hero.imageAlt': { label: 'Hero: image description', default: 'A man carrying a child away from a building destroyed by the earthquakes in Venezuela.', maxLength: 130 },
  'hero.heading': { label: 'Hero: heading', default: 'Venezuela Earthquake Relief', maxLength: 50 },
  'hero.subtext': { label: 'Hero: text', default: 'Back-to-back earthquakes have upended life across Venezuela. Your gift delivers help now.', maxLength: 140 },
  'hero.label.1': { label: 'Hero: button 1', default: 'Donate Here', maxLength: 20 },
  'sectionTitle.heading': { label: 'Section title: heading', default: '100% of net proceeds go to earthquake relief.', maxLength: 70 },
  'button.text': { label: 'Button: text', default: 'See ways to help', maxLength: 30 },
  'mediaSplit.heading': { label: 'Media split: heading', default: 'What happened', maxLength: 20 },
  'mediaSplit.text': { label: 'Media split: text', default: 'On June 24, two powerful earthquakes struck northern Venezuela less than a minute apart, the strongest the country has seen in over a century. La Guaira and Caracas were hit hardest. Thousands of families lost their homes, and many are now sleeping outside, cut off from clean water and medical care.', maxLength: 450 },
  'mediaSplit.alt.1': { label: 'Media split: image description 1', default: 'An excavator and workers clearing rubble from a collapsed building.', maxLength: 110 },
  'mediaSplit.alt.2': { label: 'Media split: image description 2', default: 'A damaged apartment tower standing above the surrounding city.', maxLength: 100 },
  'mediaSplit.alt.3': { label: 'Media split: image description 3', default: 'Two people walking out of a building wrecked by the earthquake.', maxLength: 100 },
  'mediaSplit.alt.4': { label: 'Media split: image description 4', default: 'A woman standing among the rubble of destroyed homes.', maxLength: 80 },
  'mediaSplit2.heading': { label: 'Media split 2: heading', default: 'Support Centers', maxLength: 30 },
  'mediaSplit2.text': { label: 'Media split 2: text', default: 'In the weeks after the earthquakes we opened two temporary support centres for displaced families. Both have since closed. We are now building a permanent centre in La Guaira.', maxLength: 270 },
  'mediaSplit2.imageAlt': { label: 'Media split 2: image description', default: 'Map of Venezuela marking Caracas and La Guaira, the areas hit by the June 2026 earthquakes.', maxLength: 140 },
  'appealPanel.heading': { label: 'Appeal panel: heading', default: '100% of net proceeds benefit children and families displaced by the June 2026 earthquakes in Venezuela.', maxLength: 160 },
  'appealPanel.text': { label: 'Appeal panel: text', default: "Funds raised from this campaign will go towards the construction of VVF's permanent support centre in La Guaira. When it opens it will provide shelter, nutrition and medical care to 500 displaced children and their families.", maxLength: 340 },
  'appealPanel.imageAlt': { label: 'Appeal panel: image description', default: 'Render of the planned VVF support centre in La Guaira, seen from the street.', maxLength: 120 },
  'appealPanel.caption': { label: 'Appeal panel: caption', default: 'How the centre in La Guaira will look. The centre is not built yet.', maxLength: 110 },
  'appealPanel.cardsLabel': { label: 'Appeal panel: cardsLabel', default: 'What your gift will pay for', maxLength: 50 },
  'appealPanel.title.1': { label: 'Appeal panel: title 1', default: 'Shelter', maxLength: 20 },
  'appealPanel.text.1': { label: 'Appeal panel: text 1', default: 'A safe place to stay for families whose homes were destroyed in the June 2026 earthquakes.', maxLength: 140 },
  'appealPanel.imageAlt.1': { label: 'Appeal panel: image description 1', default: 'Families arriving at the courtyard of the planned VVF support centre.', maxLength: 110 },
  'appealPanel.title.2': { label: 'Appeal panel: title 2', default: 'Medical care', maxLength: 20 },
  'appealPanel.text.2': { label: 'Appeal panel: text 2', default: 'Check-ups, medicine and treatment for children and their families at the center.', maxLength: 120 },
  'appealPanel.imageAlt.2': { label: 'Appeal panel: image description 2', default: 'A nurse examining a young girl while her mother sits beside her.', maxLength: 100 },
  'appealPanel.title.3': { label: 'Appeal panel: title 3', default: 'Nutrition', maxLength: 20 },
  'appealPanel.text.3': { label: 'Appeal panel: text 3', default: 'Daily meals for the children staying at the support center in La Guaira.', maxLength: 110 },
  'appealPanel.label.1': { label: 'Appeal panel: button 1', default: 'Give to the appeal', maxLength: 30 },
  'img.alt': { label: 'Img: image description', default: 'A man carrying a water container past earthquake-damaged houses.', maxLength: 100 },
  'sectionTitle2.heading': { label: 'Section title 2: heading', default: 'How to Help', maxLength: 20 },
  'pastelCard.eyebrow': { label: 'Pastel card: eyebrow', default: 'First', maxLength: 20 },
  'pastelCard.title': { label: 'Pastel card: title', default: 'Pray', maxLength: 20 },
  'pastelCard.body': { label: 'Pastel card: body', default: 'Join our team in daily prayer.', maxLength: 50 },
  'pastelCard2.eyebrow': { label: 'Pastel card 2: eyebrow', default: 'Second', maxLength: 20 },
  'pastelCard2.title': { label: 'Pastel card 2: title', default: 'Donate', maxLength: 20 },
  'pastelCard2.body': { label: 'Pastel card 2: body', default: 'Your financial gift allows VVF and local partners to respond promptly and effectively, bringing relief and hope.', maxLength: 170 },
  'pastelCard2.label.1': { label: 'Pastel card 2: button 1', default: 'Donate', maxLength: 20 },
  'sectionTitle3.heading': { label: 'Section title 3: heading', default: 'Keep up with our work on the ground.', maxLength: 60 },
  'h2.text': { label: 'H2: text', default: 'Point of Contact', maxLength: 30 },
  'p.text': { label: 'P: text', default: 'Is your organization interested in investing in the children and the future of Venezuela? Let’s make a positive impact together.', maxLength: 200 },
  'p2.text': { label: 'P 2: text', default: 'Weston', maxLength: 20 },
  'p3.text': { label: 'P 3: text', default: 'P.O. Box 327222, Weston, FL 33332', maxLength: 50 },
  'p5.text': { label: 'P 5: text', default: 'Business hours', maxLength: 30 },
  'p6.text': { label: 'P 6: text', default: 'Monday through Friday, 8:30 AM to 5:30 PM Eastern Time', maxLength: 90 },
  'p7.text': { label: 'P 7: text', default: 'Email anytime', maxLength: 20 },
  'a2.text': { label: 'A 2: text', default: 'info@victoriavenezuelafoundation.org', maxLength: 60 },
  'responseTimeline.heading': { label: 'Response timeline: heading', default: 'Our Response', maxLength: 20 },
  'responseTimeline.text': { label: 'Response timeline: text', default: 'Our emergency response is now completed. Our team is now building a permanent support centre in La Guaira for the children and families displaced by the earthquakes.', maxLength: 250 },
  'responseTimeline.title.1': { label: 'Response timeline: title 1', default: 'Assessment', maxLength: 20 },
  'responseTimeline.text.1': { label: 'Response timeline: text 1', default: 'Identifying the hardest-hit communities and their most urgent needs.', maxLength: 110 },
  'responseTimeline.title.2': { label: 'Response timeline: title 2', default: 'Stabilization', maxLength: 20 },
  'responseTimeline.text.2': { label: 'Response timeline: text 2', default: 'Delivering food, water, medical supplies, and shelter.', maxLength: 90 },
  'responseTimeline.title.3': { label: 'Response timeline: title 3', default: 'Strengthening', maxLength: 20 },
  'responseTimeline.text.3': { label: 'Response timeline: text 3', default: 'Helping families restore stability and routine', maxLength: 70 },
  'responseTimeline.title.4': { label: 'Response timeline: title 4', default: 'Sustainability', maxLength: 30 },
  'responseTimeline.text.4': { label: 'Response timeline: text 4', default: 'Supporting long-term recovery and resilience.', maxLength: 70 },
  'sectionTitle4.heading': { label: 'Section title 4: heading', default: 'Campaign updates', maxLength: 30 },
  'appealPanel.cards.nutritionAlt': { label: "Appeal panel: nutrition card image description", default: "Children eating a hot meal together in the centre's dining room.", maxLength: 100 },
})
