// Copy slots for / (src/lib/copy.ts). SEO defaults are the live site's
// values (src/data/page-seo.json, from the Webflow migration).
import { defineCopy, seoSlots } from '../lib/copy'

export default defineCopy('/', {
  ...seoSlots({
    title: 'Victoria Venezuela Foundation | Nutrition, Medical Care and Education',
    description: 'A 501(c)(3) nonprofit in Weston, Florida providing nutrition, medical care and education to children in Venezuela. Sponsor a child from $25 a month.',
    image: '/images/pages/57692375-vvf-home-shareimage-v2.jpg',
  }),
  'hero.imageAlt': { label: 'Hero: image description', default: 'A smiling girl at a Victoria Venezuela Foundation event.', maxLength: 90 },
  'hero.heading': { label: 'Hero: heading', default: 'Transform a child’s life in Venezuela', maxLength: 60 },
  'hero.subtext': { label: 'Hero: text', default: 'Every child deserves nutrition, medical care, and education. Victoria Venezuela Foundation delivers all three through programs that reach the children who need them most.', maxLength: 260 },
  'hero.label.1': { label: 'Hero: button 1', default: 'Sponsor a Child', maxLength: 30 },
  'hero.label.2': { label: 'Hero: button 2', default: 'Ways to Give', maxLength: 20 },
  'sectionTitle.tagline': { label: 'Section title: tagline', default: 'About Us', maxLength: 20 },
  'sectionTitle.heading': { label: 'Section title: heading', default: 'Victoria Venezuela Foundation', maxLength: 50 },
  'sectionTitle.text': { label: 'Section title: text', default: 'is a 501(c)(3) nonprofit based in Weston, Florida. We provide nutrition, medical care and education to children in Venezuela, and connect US donors with individual children through monthly sponsorship.', maxLength: 310 },
  'sectionTitle2.tagline': { label: 'Section title 2: tagline', default: 'Impact', maxLength: 20 },
  'sectionTitle2.heading': { label: 'Section title 2: heading', default: "What we've accomplished together", maxLength: 50 },
  'sectionTitle2.text': { label: 'Section title 2: text', default: 'These numbers represent real children with full bellies, steady heartbeats, and open futures. Every figure here is a life changed.', maxLength: 200 },
  'button.text': { label: 'Button: text', default: 'Read The Latest Impact Report', maxLength: 50 },
  'statTileRow.value.1': { label: 'Stat tile row: value 1', default: '77,300+', maxLength: 20 },
  'statTileRow.label.1': { label: 'Stat tile row: label 1', default: 'Meals served', maxLength: 20 },
  'statTileRow.caption.1': { label: 'Stat tile row: caption 1', default: 'Nutrition reaching hungry children daily', maxLength: 60 },
  'statTileRow.value.2': { label: 'Stat tile row: value 2', default: '1,012+', maxLength: 20 },
  'statTileRow.label.2': { label: 'Stat tile row: label 2', default: 'Medical visits for children', maxLength: 50 },
  'statTileRow.caption.2': { label: 'Stat tile row: caption 2', default: 'Health restored through our clinics', maxLength: 60 },
  'statTileRow.value.3': { label: 'Stat tile row: value 3', default: '1000+', maxLength: 20 },
  'statTileRow.label.3': { label: 'Stat tile row: label 3', default: 'Children in programs', maxLength: 30 },
  'statTileRow.caption.3': { label: 'Stat tile row: caption 3', default: 'Education opening doors to tomorrow', maxLength: 60 },
  'statTileRow.value.4': { label: 'Stat tile row: value 4', default: '41+', maxLength: 20 },
  'statTileRow.label.4': { label: 'Stat tile row: label 4', default: 'Corporate sponsors', maxLength: 30 },
  'statTileRow.caption.4': { label: 'Stat tile row: caption 4', default: 'Partners believing in this mission', maxLength: 60 },
  'sectionTitle3.tagline': { label: 'Section title 3: tagline', default: 'Programs', maxLength: 20 },
  'sectionTitle3.heading': { label: 'Section title 3: heading', default: 'How we help children in Venezuela', maxLength: 50 },
  'sectionTitle3.text': { label: 'Section title 3: text', default: 'Three essential programs working together to support underprivileged children in Venezuela.', maxLength: 140 },
  'pastelCard.eyebrow': { label: 'Pastel card: eyebrow', default: 'Nutrition', maxLength: 20 },
  'pastelCard.title': { label: 'Pastel card: title', default: 'Child Nutrition Program', maxLength: 40 },
  'pastelCard.body': { label: 'Pastel card: body', default: 'We serve hot meals and nutritional support to children facing hunger.', maxLength: 110 },
  'pastelCard2.eyebrow': { label: 'Pastel card 2: eyebrow', default: 'Medical', maxLength: 20 },
  'pastelCard2.title': { label: 'Pastel card 2: title', default: 'Healthcare Access for Children', maxLength: 50 },
  'pastelCard2.body': { label: 'Pastel card 2: body', default: 'Our clinics provide checkups, treatment, and preventive care when access is scarce.', maxLength: 130 },
  'pastelCard3.eyebrow': { label: 'Pastel card 3: eyebrow', default: 'Education', maxLength: 20 },
  'pastelCard3.title': { label: 'Pastel card 3: title', default: 'Education Support for Children', maxLength: 50 },
  'pastelCard3.body': { label: 'Pastel card 3: body', default: 'We keep children in school with supplies, support, and safe learning spaces.', maxLength: 120 },
  'impactBanner.eyebrow': { label: 'Impact banner: eyebrow', default: 'Connection', maxLength: 20 },
  'impactBanner.heading': { label: 'Impact banner: heading', default: 'Build a bond that matters', maxLength: 40 },
  'impactBanner.body': { label: 'Impact banner: body', default: "When you sponsor a child, you're not sending money into the void. You're meeting someone. You're writing letters, receiving updates, watching a real person grow. This is personal. This is lasting.", maxLength: 300 },
  'impactBanner.bullets.1': { label: 'Impact banner: bullets 1', default: 'Monthly sponsorship covers nutrition, medical care, and education', maxLength: 100 },
  'impactBanner.bullets.2': { label: 'Impact banner: bullets 2', default: 'Direct correspondence and photos from your sponsored child', maxLength: 90 },
  'impactBanner.bullets.3': { label: 'Impact banner: bullets 3', default: 'Transparent reporting on how your support makes a difference', maxLength: 90 },
  'impactBanner.imageAlt': { label: 'Impact banner: image description', default: 'Smiling boy holding cotton candy with children playing near an inflatable bounce house outdoors.', maxLength: 150 },
  'impactBanner.label.1': { label: 'Impact banner: button 1', default: 'Meet The Children', maxLength: 30 },
  'videoGrid.heading': { label: 'Video grid: heading', default: 'See our work in Venezuela', maxLength: 40 },
  'videoGrid.text': { label: 'Video grid: text', default: 'Three short videos from our programs.', maxLength: 60 },
  'videoGrid.caption.1': { label: 'Video grid: caption 1', default: 'Delivering letters to sponsored children', maxLength: 60 },
  'videoGrid.caption.2': { label: 'Video grid: caption 2', default: 'Inside our nutrition center in Terraplén', maxLength: 60 },
  'videoGrid.caption.3': { label: 'Video grid: caption 3', default: 'Our annual Christmas celebration', maxLength: 50 },
  'sectionTitle4.tagline': { label: 'Section title 4: tagline', default: 'Events & campaigns', maxLength: 30 },
  'sectionTitle4.heading': { label: 'Section title 4: heading', default: 'Join us for gatherings that build community and fuel our mission', maxLength: 100 },
  'eyebrow.text': { label: 'Eyebrow: text', default: 'Upcoming', maxLength: 20 },
  'button2.text': { label: 'Button 2: text', default: 'See all events', maxLength: 30 },
  'logoCarousel.heading': { label: 'Logo carousel: heading', default: 'Corporate Partners', maxLength: 30 },
  'programsCta.heading': { label: 'Programs cta: heading', default: 'Where your money goes', maxLength: 40 },
  'programsCta.text': { label: 'Programs cta: text', default: 'In fiscal 2025, 95% of funds went directly to programs. To date we have served more than 77,300 meals and funded more than 1,012 medical visits for children. Our full financials are published in our annual reports.', maxLength: 330 },
  'programsCta.label.1': { label: 'Programs cta: button 1', default: 'See our financials', maxLength: 30 },
})
