// Accumulates findings across migration steps into scripts/migrate/report.md.
// Each step owns one section; re-running a step replaces only its section.
import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { REPORT_PATH } from './paths.mjs'

export function createSection(title) {
  const lines = []
  return {
    line(text = '') {
      lines.push(text)
    },
    list(items) {
      for (const item of items) lines.push(`- ${item}`)
    },
    write(path = REPORT_PATH) {
      writeSection(path, title, lines.join('\n'))
    },
  }
}

export function writeSection(path, title, body) {
  const header = '# Migration report\n\nGenerated by `npm run migrate`. Each section is rewritten by its step.\n'
  const existing = existsSync(path) ? readFileSync(path, 'utf8') : header
  const marker = `## ${title}`
  const section = `${marker}\n\n${body.trim()}\n`
  const pattern = new RegExp(`## ${escape(title)}\\n[\\s\\S]*?(?=\\n## |$)`)
  const next = pattern.test(existing) ? existing.replace(pattern, section) : `${existing.trimEnd()}\n\n${section}`
  writeFileSync(path, next.endsWith('\n') ? next : `${next}\n`)
}

function escape(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')
}
