#!/usr/bin/env node
// Regenerates docs-site/src/content/docs/design-tokens.md from the token
// comments in tailwind.config.cjs. Run after changing tokens:
//   node scripts/docs-tokens.mjs
import { readFileSync, writeFileSync } from 'node:fs'

const SECTIONS = ['screens', 'colors', 'fontFamily', 'fontSize', 'lineHeight', 'borderRadius', 'spacing', 'maxWidth']
const lines = readFileSync('tailwind.config.cjs', 'utf8').split('\n')
const rows = []
let section = ''
let group = ''
let temp = false
let groupTemp = false

for (const line of lines) {
  let m
  if ((m = line.match(/^ {4,6}(\w+): \{\s*$/))) {
    section = m[1]
    group = ''
    temp = groupTemp = false
    continue
  }
  if ((m = line.match(/^ {8}('?[\w-]+'?): \{\s*$/))) {
    group = m[1].replace(/'/g, '')
    groupTemp = false
    continue
  }
  if (/^ {8}\},?\s*(\/\/.*)?$/.test(line)) {
    group = ''
    groupTemp = false
    continue
  }
  if (/^\s*\/\/.*TEMPORARY/.test(line)) {
    if (group) groupTemp = true
    else temp = true
    continue
  }
  if (/^ {2}\w/.test(line)) section = ''
  if (!SECTIONS.includes(section)) continue
  if ((m = line.match(/^\s+('?[\w-]+'?|\d+): (\[[^\]]*\]|'[^']*'|\{[^}]*\})[^/]*(?:\/\/ (.*))?$/))) {
    const key = m[1].replace(/'/g, '')
    const nested = group && /^ {10}/.test(line)
    const name = nested ? `${group}-${key}` : key
    const value = m[2].replace(/[[\]{}']/g, '').replace(/\s+/g, ' ').trim()
    const comment = m[3] ?? ''
    const isTemp = (nested ? groupTemp : temp) || /TEMPORARY/.test(comment)
    rows.push({ section, name, value, source: isTemp ? '_temporary alias_' : comment })
  }
}

let md = `---
title: Design Tokens
description: Every design token in tailwind.config.cjs and the live Webflow variable it mirrors.
---

<!-- Generated by scripts/docs-tokens.mjs from tailwind.config.cjs. Do not edit by hand. -->

Tokens are copied from the live Webflow site's CSS custom properties (\`vvfstaging.webflow.shared.css\`). Where a live value conflicts with an older project value, the live value wins. \`src/index.css\` exposes the same values as CSS variables under the live variable names. Components use these tokens only; raw hex values belong in \`tailwind.config.cjs\`.

Font roles: Nunito for headings, buttons, navigation and UI labels. Open Sans for paragraph copy (18px). Poppins only in the event sponsorship-benefits grid.
`
for (const s of SECTIONS.filter((s) => rows.some((r) => r.section === s))) {
  md += `\n## ${s}\n\n| Token | Value | Live variable / source |\n| --- | --- | --- |\n`
  for (const r of rows.filter((r) => r.section === s)) {
    md += `| \`${r.name}\` | \`${r.value.replace(/\|/g, '\\|')}\` | ${r.source.replace(/\|/g, '\\|')} |\n`
  }
}
writeFileSync('docs-site/src/content/docs/design-tokens.md', md)
console.log(`${rows.length} tokens written`)
