// Copy slots for /our-programs (src/lib/copy.ts). Defaults are the Our
// Programs design text (desktop content, used on every screen size). No live
// Spanish source: Spanish slots stay empty until marketing translates them.
// The program statistics are marketing's claims to source before publishing.
import { defineCopy, seoSlots } from '../../lib/copy'

export default defineCopy('/our-programs', {
  ...seoSlots({
    title: 'Our Programs | Victoria Venezuela Foundation',
    description: 'Nutrition, medical care and education work together to support children in Venezuela. See how our programs feed, heal and teach.',
    image: '/images/pages/programs-hero.webp',
  }),
  'hero.heading': { label: "Hero: heading", default: "Our programs transform children's lives", maxLength: 60 },
  'hero.subtext': { label: "Hero: text", default: "Nutrition, medical care, and education work together to provide holistic support. We believe every child deserves the foundation to thrive.", maxLength: 210 },
  'hero.imageAlt': { label: "Hero: image description", default: "A boy smiling at a blue table during a meal at one of our nutrition centers.", maxLength: 120 },
  'hero.cta1': { label: "Hero: first button", default: "Explore", maxLength: 20 },
  'hero.cta2': { label: "Hero: second button", default: "Donate", maxLength: 20 },
  'together.tagline': { label: "How we work together: tagline", default: "Integrated", maxLength: 20 },
  'together.heading': { label: "How we work together: heading", default: "How we work together", maxLength: 30 },
  'together.text': { label: "How we work together: text", default: "\"We believe children need more than one type of support—they need holistic care.\" Nutrition feeds the body. Medical care heals the sick. Education opens doors. Faith sustains the spirit. At Victoria Venezuela Foundation, these four pillars work as one, guided by partnerships with local churches that know their communities best.", maxLength: 500 },
  'together.cta1': { label: "How we work together: first button", default: "Learn", maxLength: 20 },
  'together.cta2': { label: "How we work together: second button", default: "Give", maxLength: 20 },
  'nutrition.tagline': { label: "Nutrition: tagline", default: "Nourishment", maxLength: 20 },
  'nutrition.heading': { label: "Nutrition: heading", default: "Nutrition program feeds hungry children", maxLength: 60 },
  'nutrition.text': { label: "Nutrition: text", default: "Nearly half of child deaths under five are due to malnutrition. In Venezuela, families struggle to put food on the table. We serve weekly nutritious meals at local church centers where children gather, learn, and grow strong. Our volunteers prepare balanced meals while sharing faith and hope with every child who walks through the door.", maxLength: 510 },
  'nutrition.cardTitle': { label: "Nutrition: photo card title", default: "Families strengthened", maxLength: 40 },
  'nutrition.cardText': { label: "Nutrition: photo card text", default: "Ordinary people discover they can do extraordinary things for their neighbors", maxLength: 120 },
  'nutrition.imageAlt': { label: "Nutrition: image description", default: "A boy eating a meal at one of our nutrition centers.", maxLength: 80 },
  'medical.tagline': { label: "Medical care: tagline", default: "Healing", maxLength: 20 },
  'medical.heading': { label: "Medical care: heading", default: "Medical care restores health and hope", maxLength: 60 },
  'medical.text': { label: "Medical care: text", default: "Seven million children die yearly from treatable diseases. In Venezuela, the healthcare system has collapsed, leaving families without access to basic care. We organize quarterly medical attention days where volunteer doctors diagnose, treat, and provide medications and vaccines to children who need them most.", maxLength: 470 },
  'medical.cardTitle': { label: "Medical care: photo card title", default: "Medical diagnosis", maxLength: 30 },
  'medical.cardText': { label: "Medical care: photo card text", default: "Professional assessment identifying conditions requiring immediate attention and care.", maxLength: 130 },
  'medical.imageAlt': { label: "Medical care: image description", default: "A volunteer nurse listening to a boy’s heartbeat during a medical attention day.", maxLength: 120 },
  'education.tagline': { label: "Education: tagline", default: "Learning", maxLength: 20 },
  'education.heading': { label: "Education: heading", default: "Education opens doors for Venezuelan children", maxLength: 70 },
  'education.text': { label: "Education: text", default: "Thirty percent of Venezuelan children under ten lack consistent access to education. Poverty, displacement, and broken systems keep them from school. We distribute school supplies and uniforms annually, provide tuition assistance to families in need, and encourage every child to complete their education.", maxLength: 460 },
  'education.cardTitle': { label: "Education: photo card title", default: "School supplies", maxLength: 30 },
  'education.cardText': { label: "Education: photo card text", default: "Financial support covering enrollment fees so families can send their children to school without hardship.", maxLength: 160 },
  'education.imageAlt': { label: "Education: image description", default: "A girl writing in her notebook at a classroom table.", maxLength: 80 },
  'program.support': { label: "Program sections: support button", default: "Support", maxLength: 20 },
  'program.gallery': { label: "Program sections: gallery button", default: "View gallery", maxLength: 20 },
  'goals.tagline': { label: "Global goals: tagline", default: "Global", maxLength: 20 },
  'goals.heading': { label: "Global goals: heading", default: "Our work aligns with global development goals", maxLength: 70 },
  'goals.text': { label: "Global goals: text", default: "Victoria Venezuela Foundation's programs directly support the United Nations Sustainable Development Goals. We work toward a world where every child has food, health, and education—the foundation for human dignity and opportunity.", maxLength: 350 },
  'goals.bullet1': { label: "Global goals: first point", default: "Zero hunger for all children", maxLength: 50 },
  'goals.bullet2': { label: "Global goals: second point", default: "Good health and well being", maxLength: 40 },
  'goals.bullet3': { label: "Global goals: third point", default: "Quality education for every child", maxLength: 50 },
  'goals.cta1': { label: "Global goals: first button", default: "Learn more", maxLength: 20 },
  'goals.cta2': { label: "Global goals: second button", default: "Explore", maxLength: 20 },
  'goals.imageAlt': { label: "Global goals: image description", default: "A smiling girl with a plate of food at a program activity.", maxLength: 90 },
  'stories.heading': { label: "Testimonials: heading (shown only when there are testimonials)", default: "Stories of transformation", maxLength: 40 },
  'stories.text': { label: "Testimonials: intro", default: "Real lives changed by real support", maxLength: 60 },
  'support.heading': { label: "Support box: heading", default: "Support our programs", maxLength: 30 },
  'support.text': { label: "Support box: text", default: "Choose how you want to make a difference in children's lives.", maxLength: 100 },
  'support.cta1': { label: "Support box: first button", default: "Sponsor", maxLength: 20 },
  'support.cta2': { label: "Support box: second button", default: "Donate", maxLength: 20 },
  'deeper.tagline': { label: "Dig deeper: tagline", default: "Next", maxLength: 20 },
  'deeper.heading': { label: "Dig deeper: heading", default: "Dig deeper into our work", maxLength: 40 },
  'deeper.text': { label: "Dig deeper: intro", default: "Explore the stories, data, and context behind what we do.", maxLength: 90 },
  'deeper.card1.eyebrow': { label: "Dig deeper card 1: tagline", default: "Results", maxLength: 20 },
  'deeper.card1.title': { label: "Dig deeper card 1: title", default: "See the impact we've made", maxLength: 40 },
  'deeper.card1.text': { label: "Dig deeper card 1: text", default: "Numbers and stories showing real change in children's lives.", maxLength: 90 },
  'deeper.card1.cta': { label: "Dig deeper card 1: button", default: "Explore", maxLength: 20 },
  'deeper.card1.imageAlt': { label: "Dig deeper card 1: image description", default: "A boy holding a plate of food outside his home.", maxLength: 80 },
  'deeper.card2.eyebrow': { label: "Dig deeper card 2: tagline", default: "Crisis", maxLength: 20 },
  'deeper.card2.title': { label: "Dig deeper card 2: title", default: "Understand Venezuela's struggle", maxLength: 50 },
  'deeper.card2.text': { label: "Dig deeper card 2: text", default: "The conditions driving our mission and the need for help.", maxLength: 90 },
  'deeper.card2.cta': { label: "Dig deeper card 2: button", default: "Learn", maxLength: 20 },
  'deeper.card2.imageAlt': { label: "Dig deeper card 2: image description", default: "A woman standing among the rubble of destroyed homes.", maxLength: 80 },
  'deeper.card3.eyebrow': { label: "Dig deeper card 3: tagline", default: "Connection", maxLength: 20 },
  'deeper.card3.title': { label: "Dig deeper card 3: title", default: "Sponsor a child today", maxLength: 40 },
  'deeper.card3.text': { label: "Dig deeper card 3: text", default: "Provide nutrition, medical care, and education year round.", maxLength: 90 },
  'deeper.card3.cta': { label: "Dig deeper card 3: button", default: "Sponsor", maxLength: 20 },
  'deeper.card3.imageAlt': { label: "Dig deeper card 3: image description", default: "A smiling girl with a plate of food at a program activity.", maxLength: 90 },
})
