// Copy slots shared by every event page (/events/*, src/lib/copy.ts): the
// template's fixed text. Content specific to one item lives on the CMS item.
import { defineCopy } from '../../lib/copy'

export default defineCopy('/events/*', {
  'hero.label.1': { label: 'Hero: button 1', default: 'Buy Tickets', maxLength: 20 },
  'hero.label.2': { label: 'Hero: button 2', default: 'See the photos', maxLength: 30 },
  'hero.label.3': { label: 'Hero: button 3', default: 'Become a Sponsor', maxLength: 30 },
  'hero.label.4': { label: 'Hero: button 4', default: 'Join us next year', maxLength: 30 },
  'logoCarousel.heading': { label: 'Logo carousel: heading', default: 'Corporate Partners', maxLength: 30 },
  'includesPanel.heading': { label: 'Includes panel: heading', default: 'Tournament Includes', maxLength: 30 },
  'sectionTitle.heading': { label: 'Section title: heading', default: 'Tickets', maxLength: 20 },
  'sectionTitle2.heading': { label: 'Section title 2: heading', default: 'Sponsor Packages', maxLength: 30 },
  'impactPanel.imageAlt': { label: 'Impact panel: image description', default: "A Victoria Venezuela Foundation volunteer checking a child's heartbeat with a stethoscope.", maxLength: 140 },
  'impactPanel.value.1': { label: 'Impact panel: value 1', default: '77,300+', maxLength: 20 },
  'impactPanel.label.1': { label: 'Impact panel: label 1', default: 'Meals served to children at risk', maxLength: 50 },
  'impactPanel.value.2': { label: 'Impact panel: value 2', default: '1,012', maxLength: 20 },
  'impactPanel.label.2': { label: 'Impact panel: label 2', default: 'medical visits for children', maxLength: 50 },
  'impactPanel.value.3': { label: 'Impact panel: value 3', default: '41+', maxLength: 20 },
  'impactPanel.label.3': { label: 'Impact panel: label 3', default: 'corporate sponsors investing in support programs for children and Venezuela', maxLength: 120 },
  'sectionTitle3.heading': { label: 'Section title 3: heading', default: 'FAQs & Contact info', maxLength: 30 },
  'contactCta.label.1': { label: 'Contact cta: button 1', default: 'Buy Tickets', maxLength: 20 },
  'button.text': { label: 'Button: text', default: 'See the photos', maxLength: 30 },
  'sectionTitle5.tagline': { label: 'Section title 5: tagline', default: 'Memories', maxLength: 20 },
  'sectionTitle5.heading': { label: 'Section title 5: heading', default: 'Event photos', maxLength: 20 },
  'sectionTitle5.text': { label: 'Section title 5: text', default: 'Moments from the course, the auction and the celebration.', maxLength: 90 },
  'logoCarousel2.heading': { label: 'Logo carousel 2: heading', default: 'Thank you to our sponsors', maxLength: 40 },
  'programsCta.heading': { label: 'Programs cta: heading', default: 'Mark your calendar', maxLength: 30 },
  'programsCta.text': { label: 'Programs cta: text', default: "Next year's tournament is on its way. See the date and venue, and save your spot.", maxLength: 130 },
  'programsCta.label.1': { label: 'Programs cta: button 1', default: 'Contact us', maxLength: 20 },
  'sectionTitle6.tagline': { label: 'Section title 6: tagline', default: 'Support', maxLength: 20 },
  'sectionTitle6.heading': { label: 'Section title 6: heading', default: "Can't wait until next year?", maxLength: 50 },
  'sectionTitle6.text': { label: 'Section title 6: text', default: 'Children in Venezuela need help today. Here are three ways to make a difference right now.', maxLength: 140 },
  'pastelCard.title': { label: 'Pastel card: title', default: 'Sponsor a child', maxLength: 30 },
  'pastelCard.body': { label: 'Pastel card: body', default: 'Build a direct relationship and change a young life.', maxLength: 80 },
  'pastelCard.label.1': { label: 'Pastel card: button 1', default: 'Sponsor', maxLength: 20 },
  'pastelCard2.title': { label: 'Pastel card 2: title', default: 'Make a donation', maxLength: 30 },
  'pastelCard2.body': { label: 'Pastel card 2: body', default: 'Fund nutrition, medical care and education programs today.', maxLength: 90 },
  'pastelCard2.label.1': { label: 'Pastel card 2: button 1', default: 'Donate', maxLength: 20 },
  'pastelCard3.title': { label: 'Pastel card 3: title', default: 'Corporate sponsorships', maxLength: 40 },
  'pastelCard3.body': { label: 'Pastel card 3: body', default: 'Align your business with a mission that matters all year.', maxLength: 90 },
  'pastelCard3.label.1': { label: 'Pastel card 3: button 1', default: 'Partner with us', maxLength: 30 },
  'seo.titleFallback': { label: 'Browser tab title when the event has no SEO title ({title} is replaced)', default: '{title} | Victoria Venezuela Foundation', maxLength: 60 },
  'memories.heading': { label: 'Upcoming event: last year\'s photos heading ({year} is replaced)', default: '{year} Memories', maxLength: 40 },
  'contact.heading': { label: 'Upcoming event: contact box heading ({date} is replaced with the event day)', default: 'Golf. Give. Transform lives in Venezuela. Join us {date}!', maxLength: 90 },
  'recap.tagline': { label: 'Past event: results tagline', default: 'Results', maxLength: 30 },
  'recap.heading': { label: 'Past event: results heading', default: 'What we did together', maxLength: 50 },
  'recap.text': { label: 'Past event: results text', default: 'Here is what one day on the course made possible for children in Venezuela.', maxLength: 160 },
  'programsCta.label.2': { label: "Programs cta: button 2", default: "See next year's tournament", maxLength: 40 },
})
